// 30 curated books with full metadata for BookSmart
const seedData = [
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    category: "Self-Help",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    tags: [
      { label: "Focus", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Habits", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Motivated", "Burned Out"],
    problems: ["Lack of Focus", "Want to Start Reading"],
    readingLevel: "Beginner",
    readingTime: "5-6 hrs",
    why: "Breaks down the science of habit formation into simple, actionable frameworks that stick.",
    shouldRead: "Anyone wanting to build good habits and break bad ones systematically.",
    shouldNot: "People looking for instant motivation — this is about systems, not hype.",
    outcome: "A clear system that makes good behaviors automatic over time.",
    amazonLink: "https://www.amazon.in/s?k=Atomic+Habits+James+Clear",
    flipkartLink: "https://www.flipkart.com/search?q=Atomic+Habits+James+Clear",
    rating: 4.8,
    featured: true,
    readingPaths: ["Student", "Professional"]
  },
  {
    title: "Ikigai",
    author: "Héctor García",
    isbn: "9780525559474",
    category: "Life Philosophy",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    tags: [
      { label: "Purpose", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Happiness", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" }
    ],
    moods: ["Confused", "Feeling Low"],
    problems: ["No Life Direction", "Career Confusion"],
    readingLevel: "Beginner",
    readingTime: "3-4 hrs",
    why: "Teaches the Japanese concept of finding joy and meaning in everyday life.",
    shouldRead: "Anyone feeling lost about their purpose in life.",
    shouldNot: "People looking for career step-by-step guides — this is philosophical.",
    outcome: "Clarity on what makes life worth living for you personally.",
    amazonLink: "https://www.amazon.in/s?k=Ikigai+Hector+Garcia",
    flipkartLink: "https://www.flipkart.com/search?q=Ikigai+Hector+Garcia",
    rating: 4.5,
    featured: true,
    readingPaths: ["Beginner", "Job Seeker"]
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    isbn: "9781612680194",
    category: "Finance",
    language: "Hinglish",
    langColor: "#7c5cbf",
    langBg: "rgba(124,92,191,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781612680194-L.jpg",
    tags: [
      { label: "Money", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Mindset", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["Money & Finance", "Career Confusion"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "Changes how you think about money, assets, and financial independence.",
    shouldRead: "Anyone wanting to understand money, investing and financial freedom.",
    shouldNot: "Those looking for specific investment strategies — this is mindset-focused.",
    outcome: "A completely different perspective on earning, saving, and investing.",
    amazonLink: "https://www.amazon.in/s?k=Rich+Dad+Poor+Dad+Robert+Kiyosaki",
    flipkartLink: "https://www.flipkart.com/search?q=Rich+Dad+Poor+Dad+Robert+Kiyosaki",
    rating: 4.6,
    featured: true,
    readingPaths: ["Student", "Job Seeker"]
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    isbn: "9781455586691",
    category: "Productivity",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
    tags: [
      { label: "Focus", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Career", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Motivated", "Burned Out"],
    problems: ["Lack of Focus", "Career Confusion"],
    readingLevel: "Intermediate",
    readingTime: "5-7 hrs",
    why: "Proves that focused, distraction-free work is the superpower of the modern age.",
    shouldRead: "Working professionals, students preparing for competitive exams.",
    shouldNot: "Casual readers — this requires implementing strict practices.",
    outcome: "A structured method to produce high-quality work consistently.",
    amazonLink: "https://www.amazon.in/s?k=Deep+Work+Cal+Newport",
    flipkartLink: "https://www.flipkart.com/search?q=Deep+Work+Cal+Newport",
    rating: 4.7,
    featured: true,
    readingPaths: ["Professional", "Student"]
  },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    isbn: "9780671027032",
    category: "Communication",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg",
    tags: [
      { label: "Social Skills", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" },
      { label: "Leadership", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Confused", "Feeling Low"],
    problems: ["Communication", "Low Confidence"],
    readingLevel: "Beginner",
    readingTime: "5-6 hrs",
    why: "Timeless principles that make people respond positively and trust you.",
    shouldRead: "Anyone who wants to build better relationships personally and professionally.",
    shouldNot: "People expecting manipulation tactics — this is about genuine human connection.",
    outcome: "You'll naturally build trust, rapport, and influence with people around you.",
    amazonLink: "https://www.amazon.in/s?k=How+to+Win+Friends+Dale+Carnegie",
    flipkartLink: "https://www.flipkart.com/search?q=How+to+Win+Friends+Dale+Carnegie",
    rating: 4.7,
    featured: true,
    readingPaths: ["Job Seeker", "Professional"]
  },
  {
    title: "You Can Win",
    author: "Shiv Khera",
    isbn: "9780070481718",
    category: "Motivation",
    language: "Hinglish",
    langColor: "#7c5cbf",
    langBg: "rgba(124,92,191,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780070481718-L.jpg",
    tags: [
      { label: "Confidence", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Beginners", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Feeling Low", "Motivated"],
    problems: ["Low Confidence", "Want to Start Reading"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "Simple, direct language with real-life stories that inspire action.",
    shouldRead: "Students, beginners, and anyone who needs a confidence boost.",
    shouldNot: "Advanced readers seeking deep psychological insight.",
    outcome: "A renewed belief in yourself and clear steps to build confidence.",
    amazonLink: "https://www.amazon.in/s?k=You+Can+Win+Shiv+Khera",
    flipkartLink: "https://www.flipkart.com/search?q=You+Can+Win+Shiv+Khera",
    rating: 4.3,
    featured: true,
    readingPaths: ["Student", "Beginner"]
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    category: "Fiction/Inspiration",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    tags: [
      { label: "Dreams", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Journey", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" }
    ],
    moods: ["Confused", "Feeling Low"],
    problems: ["No Life Direction", "Career Confusion"],
    readingLevel: "Beginner",
    readingTime: "3-4 hrs",
    why: "A fable about following your dreams and listening to your heart.",
    shouldRead: "Anyone at a crossroads in life, feeling lost or uninspired.",
    shouldNot: "People who want practical step-by-step career advice.",
    outcome: "A renewed sense of purpose and courage to pursue your personal legend.",
    amazonLink: "https://www.amazon.in/s?k=The+Alchemist+Paulo+Coelho",
    flipkartLink: "https://www.flipkart.com/search?q=The+Alchemist+Paulo+Coelho",
    rating: 4.6,
    featured: false,
    readingPaths: ["Beginner", "Student"]
  },
  {
    title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    isbn: "9788173711466",
    category: "Biography",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg",
    tags: [
      { label: "Inspiration", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "India", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Feeling Low", "Motivated"],
    problems: ["Low Confidence", "Career Confusion"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "The inspiring autobiography of India's missile man who rose from poverty to become President.",
    shouldRead: "Indian students and youth who need inspiration against all odds.",
    shouldNot: "People looking for technical career guides.",
    outcome: "Deep inspiration and belief that background doesn't determine destiny.",
    amazonLink: "https://www.amazon.in/s?k=Wings+of+Fire+APJ+Abdul+Kalam",
    flipkartLink: "https://www.flipkart.com/search?q=Wings+of+Fire+APJ+Abdul+Kalam",
    rating: 4.5,
    featured: false,
    readingPaths: ["Student", "Beginner"]
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    isbn: "9781585424337",
    category: "Success & Finance",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg",
    tags: [
      { label: "Wealth", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Success", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Motivated", "Confused"],
    problems: ["Money & Finance", "Low Confidence"],
    readingLevel: "Beginner",
    readingTime: "6-8 hrs",
    why: "Distills the success principles of 500+ millionaires into 13 actionable laws.",
    shouldRead: "Anyone who wants to understand the mindset behind wealth and success.",
    shouldNot: "People expecting a 'get rich quick' formula.",
    outcome: "A burning desire and a concrete plan for achieving your biggest goals.",
    amazonLink: "https://www.amazon.in/s?k=Think+and+Grow+Rich+Napoleon+Hill",
    flipkartLink: "https://www.flipkart.com/search?q=Think+and+Grow+Rich+Napoleon+Hill",
    rating: 4.4,
    featured: false,
    readingPaths: ["Job Seeker", "Professional"]
  },
  {
    title: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    isbn: "9780735204553",
    category: "Psychology",
    language: "Hindi",
    langColor: "#e85d3a",
    langBg: "rgba(232,93,58,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780735204553-L.jpg",
    tags: [
      { label: "Mind", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" },
      { label: "Healing", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" }
    ],
    moods: ["Feeling Low", "Confused"],
    problems: ["Low Confidence", "Emotional Stress"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "Explains how your subconscious mind shapes your reality and how to reprogram it.",
    shouldRead: "Anyone struggling with self-doubt, fear, or negative thought patterns.",
    shouldNot: "Strictly scientific readers — this has spiritual psychology elements.",
    outcome: "Tools to reprogram your mind for confidence, healing, and success.",
    amazonLink: "https://www.amazon.in/s?k=Power+of+Subconscious+Mind+Joseph+Murphy",
    flipkartLink: "https://www.flipkart.com/search?q=Power+of+Subconscious+Mind+Joseph+Murphy",
    rating: 4.3,
    featured: false,
    readingPaths: ["Beginner", "Student"]
  },
  {
    title: "Zero to One",
    author: "Peter Thiel",
    isbn: "9780804139021",
    category: "Entrepreneurship",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg",
    tags: [
      { label: "Startup", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Innovation", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Motivated", "Confused"],
    problems: ["Career Confusion", "Money & Finance"],
    readingLevel: "Intermediate",
    readingTime: "4-5 hrs",
    why: "Challenges conventional thinking about startups and teaches how to create truly new things.",
    shouldRead: "Aspiring entrepreneurs, innovators, and anyone building something from scratch.",
    shouldNot: "People looking for a step-by-step startup guide — this is philosophy-heavy.",
    outcome: "A completely new way of thinking about innovation and competition.",
    amazonLink: "https://www.amazon.in/s?k=Zero+to+One+Peter+Thiel",
    flipkartLink: "https://www.flipkart.com/search?q=Zero+to+One+Peter+Thiel",
    rating: 4.5,
    featured: false,
    readingPaths: ["Professional", "Job Seeker"]
  },
  {
    title: "The 5 AM Club",
    author: "Robin Sharma",
    isbn: "9781443456623",
    category: "Productivity",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781443456623-L.jpg",
    tags: [
      { label: "Morning", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Routine", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Motivated", "Burned Out"],
    problems: ["Lack of Focus", "Want to Start Reading"],
    readingLevel: "Beginner",
    readingTime: "5-6 hrs",
    why: "Uses a story format to teach the 20/20/20 morning routine formula.",
    shouldRead: "Anyone who wants to transform their mornings and build elite habits.",
    shouldNot: "Night owls or people who hate self-help fiction hybrids.",
    outcome: "A morning routine that gives you energy, focus, and peace before the world wakes up.",
    amazonLink: "https://www.amazon.in/s?k=The+5+AM+Club+Robin+Sharma",
    flipkartLink: "https://www.flipkart.com/search?q=The+5+AM+Club+Robin+Sharma",
    rating: 4.2,
    featured: false,
    readingPaths: ["Student", "Professional"]
  },
  {
    title: "Mindset: The New Psychology of Success",
    author: "Carol Dweck",
    isbn: "9780345472328",
    category: "Psychology",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg",
    tags: [
      { label: "Growth", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Psychology", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["Low Confidence", "Career Confusion"],
    readingLevel: "Intermediate",
    readingTime: "5-6 hrs",
    why: "Research-backed proof that your mindset — fixed vs growth — determines everything.",
    shouldRead: "Students, parents, teachers, and anyone who wants to learn and grow.",
    shouldNot: "People looking for quick motivation hits — this is science-based.",
    outcome: "A shift from 'I can't do this' to 'I can't do this YET'.",
    amazonLink: "https://www.amazon.in/s?k=Mindset+Carol+Dweck",
    flipkartLink: "https://www.flipkart.com/search?q=Mindset+Carol+Dweck",
    rating: 4.5,
    featured: false,
    readingPaths: ["Student", "Job Seeker"]
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    category: "History/Philosophy",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    tags: [
      { label: "History", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" },
      { label: "Big Ideas", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["No Life Direction"],
    readingLevel: "Intermediate",
    readingTime: "10-12 hrs",
    why: "Changes your entire perspective on what it means to be human.",
    shouldRead: "Curious minds who want to understand where humanity came from and where we're going.",
    shouldNot: "People looking for self-help — this is intellectual history.",
    outcome: "A mind-expanding understanding of human civilization and your place in it.",
    amazonLink: "https://www.amazon.in/s?k=Sapiens+Yuval+Noah+Harari",
    flipkartLink: "https://www.flipkart.com/search?q=Sapiens+Yuval+Noah+Harari",
    rating: 4.7,
    featured: false,
    readingPaths: ["Professional", "Student"]
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    isbn: "9780062457714",
    category: "Self-Help",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    tags: [
      { label: "Honesty", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" },
      { label: "Real Talk", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Burned Out", "Feeling Low"],
    problems: ["Emotional Stress", "Low Confidence"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "Brutally honest counter-culture self-help that rejects toxic positivity.",
    shouldRead: "Anyone exhausted by forced positivity and needing real talk.",
    shouldNot: "Sensitive readers — language is intentionally blunt and profane.",
    outcome: "Freedom from caring about things that don't matter + clarity on what does.",
    amazonLink: "https://www.amazon.in/s?k=Subtle+Art+Not+Giving+Mark+Manson",
    flipkartLink: "https://www.flipkart.com/search?q=Subtle+Art+Not+Giving+Mark+Manson",
    rating: 4.3,
    featured: false,
    readingPaths: ["Job Seeker", "Beginner"]
  },
  {
    title: "Can't Hurt Me",
    author: "David Goggins",
    isbn: "9781544512266",
    category: "Mental Toughness",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781544512266-L.jpg",
    tags: [
      { label: "Grit", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Extreme", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" }
    ],
    moods: ["Motivated", "Burned Out"],
    problems: ["Low Confidence", "Lack of Focus"],
    readingLevel: "Beginner",
    readingTime: "6-7 hrs",
    why: "The most intense story of mental toughness ever written — from abuse victim to Navy SEAL.",
    shouldRead: "Anyone who feels they've hit a wall and need extreme motivation.",
    shouldNot: "Readers looking for gentle, soft motivation — this is brutal and intense.",
    outcome: "The belief that you can push past any mental limit you thought you had.",
    amazonLink: "https://www.amazon.in/s?k=Cant+Hurt+Me+David+Goggins",
    flipkartLink: "https://www.flipkart.com/search?q=Cant+Hurt+Me+David+Goggins",
    rating: 4.8,
    featured: false,
    readingPaths: ["Professional", "Student"]
  },
  {
    title: "Start With Why",
    author: "Simon Sinek",
    isbn: "9781591846444",
    category: "Leadership",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg",
    tags: [
      { label: "Purpose", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Leadership", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["Career Confusion", "No Life Direction"],
    readingLevel: "Intermediate",
    readingTime: "5-6 hrs",
    why: "Explains why some leaders and companies inspire while others don't — it starts with purpose.",
    shouldRead: "Aspiring leaders, entrepreneurs, and anyone confused about their life direction.",
    shouldNot: "People looking for tactical how-to business advice.",
    outcome: "Clarity on your personal 'why' and how to communicate it to inspire others.",
    amazonLink: "https://www.amazon.in/s?k=Start+With+Why+Simon+Sinek",
    flipkartLink: "https://www.flipkart.com/search?q=Start+With+Why+Simon+Sinek",
    rating: 4.5,
    featured: false,
    readingPaths: ["Professional", "Job Seeker"]
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "9780857197689",
    category: "Finance/Psychology",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    tags: [
      { label: "Money", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Behavior", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["Money & Finance", "Career Confusion"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "Short, timeless lessons about how people think about wealth and making financial decisions.",
    shouldRead: "Anyone who wants to understand their own relationship with money.",
    shouldNot: "People seeking specific investment strategies or stock tips.",
    outcome: "A healthier, more rational approach to financial decisions.",
    amazonLink: "https://www.amazon.in/s?k=Psychology+of+Money+Morgan+Housel",
    flipkartLink: "https://www.flipkart.com/search?q=Psychology+of+Money+Morgan+Housel",
    rating: 4.7,
    featured: false,
    readingPaths: ["Student", "Professional"]
  },
  {
    title: "Losing My Virginity",
    author: "Richard Branson",
    isbn: "9780307720740",
    category: "Entrepreneurship/Biography",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780307720740-L.jpg",
    tags: [
      { label: "Adventure", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" },
      { label: "Business", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Motivated", "Confused"],
    problems: ["Career Confusion", "Low Confidence"],
    readingLevel: "Intermediate",
    readingTime: "8-10 hrs",
    why: "The wild, unfiltered story of how Richard Branson built the Virgin empire from nothing.",
    shouldRead: "Aspiring entrepreneurs who want real stories of failure and success.",
    shouldNot: "People looking for structured business lessons — this is a rollercoaster memoir.",
    outcome: "Permission to think big and take bold risks in business.",
    amazonLink: "https://www.amazon.in/s?k=Losing+My+Virginity+Richard+Branson",
    flipkartLink: "https://www.flipkart.com/search?q=Losing+My+Virginity+Richard+Branson",
    rating: 4.2,
    featured: false,
    readingPaths: ["Professional", "Job Seeker"]
  },
  {
    title: "Eat That Frog",
    author: "Brian Tracy",
    isbn: "9781626569416",
    category: "Productivity",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781626569416-L.jpg",
    tags: [
      { label: "Action", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Quick Read", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Motivated", "Burned Out"],
    problems: ["Lack of Focus", "Career Confusion"],
    readingLevel: "Beginner",
    readingTime: "2-3 hrs",
    why: "21 practical techniques to stop procrastinating and get more done in less time.",
    shouldRead: "Anyone who procrastinates and wants practical, immediate solutions.",
    shouldNot: "People looking for deep psychological insight into procrastination.",
    outcome: "A daily system that ensures your most important tasks get done first.",
    amazonLink: "https://www.amazon.in/s?k=Eat+That+Frog+Brian+Tracy",
    flipkartLink: "https://www.flipkart.com/search?q=Eat+That+Frog+Brian+Tracy",
    rating: 4.1,
    featured: false,
    readingPaths: ["Student", "Job Seeker"]
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    isbn: "9780743269513",
    category: "Self-Help/Leadership",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780743269513-L.jpg",
    tags: [
      { label: "Habits", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Character", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Motivated", "Confused"],
    problems: ["Career Confusion", "Communication"],
    readingLevel: "Intermediate",
    readingTime: "8-10 hrs",
    why: "The classic framework for personal and professional effectiveness built on character.",
    shouldRead: "Working professionals and students wanting to build lasting success habits.",
    shouldNot: "People wanting quick fixes — this requires sustained practice.",
    outcome: "A complete framework for living with purpose, integrity, and effectiveness.",
    amazonLink: "https://www.amazon.in/s?k=7+Habits+Highly+Effective+People+Covey",
    flipkartLink: "https://www.flipkart.com/search?q=7+Habits+Highly+Effective+People+Covey",
    rating: 4.6,
    featured: false,
    readingPaths: ["Professional", "Job Seeker"]
  },
  {
    title: "Good to Great",
    author: "Jim Collins",
    isbn: "9780066620992",
    category: "Business/Leadership",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg",
    tags: [
      { label: "Strategy", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" },
      { label: "Excellence", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Motivated"],
    problems: ["Career Confusion", "Money & Finance"],
    readingLevel: "Advanced",
    readingTime: "8-10 hrs",
    why: "Research-backed study of why some companies make the leap from good to great.",
    shouldRead: "Business leaders, managers, and MBA students.",
    shouldNot: "General beginners — this is business-focused and research-heavy.",
    outcome: "Frameworks for building truly great organizations and leading at the highest level.",
    amazonLink: "https://www.amazon.in/s?k=Good+to+Great+Jim+Collins",
    flipkartLink: "https://www.flipkart.com/search?q=Good+to+Great+Jim+Collins",
    rating: 4.4,
    featured: false,
    readingPaths: ["Professional"]
  },
  {
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    isbn: "9789350093481",
    category: "Spirituality/Self-Help",
    language: "Hinglish",
    langColor: "#7c5cbf",
    langBg: "rgba(124,92,191,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9789350093481-L.jpg",
    tags: [
      { label: "Wisdom", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Peace", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Burned Out", "Confused"],
    problems: ["Emotional Stress", "No Life Direction"],
    readingLevel: "Beginner",
    readingTime: "4-5 hrs",
    why: "A fable about a lawyer who gives it all up to find wisdom, purpose, and inner peace.",
    shouldRead: "Anyone feeling empty despite outward success, or burned out by hustle culture.",
    shouldNot: "Readers who prefer non-fiction facts over story-based lessons.",
    outcome: "A philosophy for living fully — balancing ambition with inner peace.",
    amazonLink: "https://www.amazon.in/s?k=Monk+Who+Sold+His+Ferrari+Robin+Sharma",
    flipkartLink: "https://www.flipkart.com/search?q=Monk+Who+Sold+His+Ferrari+Robin+Sharma",
    rating: 4.3,
    featured: false,
    readingPaths: ["Beginner", "Professional"]
  },
  {
    title: "Awaken the Giant Within",
    author: "Tony Robbins",
    isbn: "9780671791544",
    category: "Motivation/Psychology",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780671791544-L.jpg",
    tags: [
      { label: "Power", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" },
      { label: "Transform", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Feeling Low", "Motivated"],
    problems: ["Low Confidence", "Emotional Stress"],
    readingLevel: "Intermediate",
    readingTime: "8-10 hrs",
    why: "Tony Robbins' master framework for taking control of your mind, emotions, and life.",
    shouldRead: "People serious about total life transformation — physical, emotional, financial.",
    shouldNot: "Casual readers — this is long and demands active participation.",
    outcome: "Control over your emotional state, beliefs, and life direction.",
    amazonLink: "https://www.amazon.in/s?k=Awaken+Giant+Within+Tony+Robbins",
    flipkartLink: "https://www.flipkart.com/search?q=Awaken+Giant+Within+Tony+Robbins",
    rating: 4.4,
    featured: false,
    readingPaths: ["Professional", "Job Seeker"]
  },
  {
    title: "The Secret",
    author: "Rhonda Byrne",
    isbn: "9781582701707",
    category: "Self-Help/Spirituality",
    language: "Hindi",
    langColor: "#e85d3a",
    langBg: "rgba(232,93,58,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781582701707-L.jpg",
    tags: [
      { label: "Attraction", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" },
      { label: "Positive", color: "#f5a623", bg: "rgba(245,166,35,0.1)" }
    ],
    moods: ["Feeling Low", "Confused"],
    problems: ["Low Confidence", "No Life Direction"],
    readingLevel: "Beginner",
    readingTime: "3-4 hrs",
    why: "Introduces the law of attraction and the power of positive thinking.",
    shouldRead: "Beginners exploring self-help, spiritual readers, people wanting hope.",
    shouldNot: "Scientific skeptics — this has no empirical backing and is highly criticized.",
    outcome: "A more positive mindset and awareness of your thoughts' impact on your life.",
    amazonLink: "https://www.amazon.in/s?k=The+Secret+Rhonda+Byrne",
    flipkartLink: "https://www.flipkart.com/search?q=The+Secret+Rhonda+Byrne",
    rating: 3.9,
    featured: false,
    readingPaths: ["Beginner"]
  },
  {
    title: "The Courage to Be Disliked",
    author: "Ichiro Kishimi",
    isbn: "9781501197277",
    category: "Psychology/Philosophy",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781501197277-L.jpg",
    tags: [
      { label: "Freedom", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "Self-Worth", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" }
    ],
    moods: ["Feeling Low", "Confused"],
    problems: ["Low Confidence", "Emotional Stress"],
    readingLevel: "Intermediate",
    readingTime: "4-5 hrs",
    why: "Uses Adlerian psychology in a dialogue format to challenge everything you believe about happiness.",
    shouldRead: "People pleasers, overthinkers, anyone seeking emotional independence.",
    shouldNot: "Those wanting quick self-help tips — this is a philosophical dialogue.",
    outcome: "The courage to live your own life without needing others' approval.",
    amazonLink: "https://www.amazon.in/s?k=Courage+to+Be+Disliked+Kishimi",
    flipkartLink: "https://www.flipkart.com/search?q=Courage+to+Be+Disliked+Kishimi",
    rating: 4.5,
    featured: false,
    readingPaths: ["Student", "Beginner"]
  },
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "9780307887894",
    category: "Entrepreneurship",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    tags: [
      { label: "Startup", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" },
      { label: "MVP", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Motivated", "Confused"],
    problems: ["Career Confusion", "Money & Finance"],
    readingLevel: "Intermediate",
    readingTime: "5-6 hrs",
    why: "The validated learning approach to building businesses that actually work.",
    shouldRead: "First-time founders, product managers, and innovation teams.",
    shouldNot: "People not interested in business building or product development.",
    outcome: "A scientific methodology for launching and growing startups efficiently.",
    amazonLink: "https://www.amazon.in/s?k=Lean+Startup+Eric+Ries",
    flipkartLink: "https://www.flipkart.com/search?q=Lean+Startup+Eric+Ries",
    rating: 4.3,
    featured: false,
    readingPaths: ["Professional", "Job Seeker"]
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    isbn: "9780807014295",
    category: "Psychology/Philosophy",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
    tags: [
      { label: "Meaning", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Resilience", color: "#00e5a0", bg: "rgba(0,229,160,0.1)" }
    ],
    moods: ["Feeling Low", "Confused"],
    problems: ["Emotional Stress", "No Life Direction"],
    readingLevel: "Intermediate",
    readingTime: "3-4 hrs",
    why: "A Holocaust survivor's profound insight into finding meaning even in the worst suffering.",
    shouldRead: "Anyone going through deep pain or existential crisis.",
    shouldNot: "People wanting light, upbeat motivational reading.",
    outcome: "The unshakeable conviction that your life has meaning, no matter the circumstances.",
    amazonLink: "https://www.amazon.in/s?k=Mans+Search+for+Meaning+Viktor+Frankl",
    flipkartLink: "https://www.flipkart.com/search?q=Mans+Search+for+Meaning+Viktor+Frankl",
    rating: 4.8,
    featured: false,
    readingPaths: ["Student", "Beginner"]
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "9780374533557",
    category: "Psychology/Decision Making",
    language: "English",
    langColor: "#1a5fa8",
    langBg: "rgba(26,95,168,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    tags: [
      { label: "Cognition", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" },
      { label: "Bias", color: "#ff5fa0", bg: "rgba(255,95,160,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["Career Confusion", "Lack of Focus"],
    readingLevel: "Advanced",
    readingTime: "10-12 hrs",
    why: "Nobel laureate reveals the two systems of thinking that drive every decision you make.",
    shouldRead: "Intellectually curious people who want to understand how they think.",
    shouldNot: "Casual readers — this is dense, academic, and very long.",
    outcome: "Awareness of your own cognitive biases and better decision-making ability.",
    amazonLink: "https://www.amazon.in/s?k=Thinking+Fast+and+Slow+Kahneman",
    flipkartLink: "https://www.flipkart.com/search?q=Thinking+Fast+and+Slow+Kahneman",
    rating: 4.6,
    featured: false,
    readingPaths: ["Professional"]
  },
  {
    title: "Chanakya Neeti",
    author: "Chanakya (B. K. Chaturvedi)",
    isbn: "9788128812187",
    category: "Philosophy/Strategy",
    language: "Hindi",
    langColor: "#e85d3a",
    langBg: "rgba(232,93,58,0.15)",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9788128812187-L.jpg",
    tags: [
      { label: "Ancient Wisdom", color: "#f5a623", bg: "rgba(245,166,35,0.1)" },
      { label: "Strategy", color: "#4f8dff", bg: "rgba(79,141,255,0.1)" }
    ],
    moods: ["Confused", "Motivated"],
    problems: ["Career Confusion", "Communication"],
    readingLevel: "Beginner",
    readingTime: "3-4 hrs",
    why: "Ancient Indian wisdom on leadership, strategy, and life management that's still relevant today.",
    shouldRead: "Indian readers interested in ancient philosophy applied to modern life.",
    shouldNot: "Readers expecting contemporary self-help language and examples.",
    outcome: "Time-tested principles for navigating relationships, career, and decision-making.",
    amazonLink: "https://www.amazon.in/s?k=Chanakya+Neeti+Hindi",
    flipkartLink: "https://www.flipkart.com/search?q=Chanakya+Neeti+Hindi",
    rating: 4.2,
    featured: false,
    readingPaths: ["Student", "Professional"]
  }
];

module.exports = seedData;
