name: Docker Build Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Dummy Environment Variables
      run: |
        cp server/.env.example server/.env
        touch client/.env

    - name: Validate Docker Compose Config
      run: docker compose config
      
    - name: Build Docker Images
      run: docker compose build
